export const GET_TOP_TRACKS_START = 'GET_TOP_TRACKS';
export const GET_TOP_TRACKS_SUCCESS = 'GET_TOP_TRACKS_SUCCESS';
export const GET_TOP_TRACKS_ERROR = 'GET_TOP_TRACKS_ERROR';

export const GET_TOP_ARTIST_START = 'GET_TOP_ARTIST_START';
export const GET_TOP_ARTIST_SUCCESS = 'GET_TOP_ARTIST_SUCCESS';
export const GET_TOP_ARTIST_ERROR = 'GET_TOP_ARTIST_ERROR';

export const SET_FORM = 'SET_FORM';
