export const GET_TOP_TRACKS_START = 'GET_TOP_TRACKS';
export const GET_TOP_TRACKS_SUCCESS = 'GET_TOP_TRACKS_SUCCESS';
export const GET_TOP_TRACKS_ERROR = 'GET_TOP_TRACKS_ERROR';

export const GET_TOP_ARTISTS_START = 'GET_TOP_ARTISTS_START';
export const GET_TOP_ARTISTS_SUCCESS = 'GET_TOP_ARTISTS_SUCCESS';
export const GET_TOP_ARTISTS_ERROR = 'GET_TOP_ARTISTS_ERROR';




